---
- name: Bootstrap python
  hosts: computers
  gather_facts: no
  tasks:
    - raw: sudo xbps-install python -Sy
      ignore_errors: yes

- name: Base Configuration
  hosts: computers
  tasks:
    - name: Add lug mirror
      become: true
      lineinfile:
        dest: '/etc/xbps.d/00-repository-main.conf'
        line: 'repository=https://lug.utdallas.edu/mirror/void/current'
        create: yes

    - name: Install packages
      become: true
      xbps:
        name:
          - dbus
          - dmenu
          - firefox
          - git-all
          - i3
          - i3status
          - lightdm
          - lightdm-gtk3-greeter
          - neovim
          - python-neovim
          - python3.4-neovim
          - rxvt-unicode
          - xorg
          - zsh

    - name: Enable services
      file: src=/etc/sv/{{ item }} dest=/var/service/{{ item }} state=link
      become: true
      with_items:
        - dbus
        - lightdm
        - dhcpcd

    - name: Install Dotfiles
      git:
        repo: 'https://github.com/dinoocch/dotfiles.git'
        dest: /home/vagrant/dotfiles
        accept_hostkey: true

    - name: Create Directories
      file: path=/home/vagrant/{{ item }} state=directory mode=0750
      with_items:
        - '.config'
        - '.config/nvim'
        - '.config/nvim/autoload'
        - '.vim'
        - '.vim/backups'
        - '.vim/swaps'
        - '.vim/undo'
        - '.i3'

    - name: Enable dotfiles
      file: src=/home/vagrant/dotfiles/{{ item.from }} dest=/home/vagrant/{{ item.to }} state=link
      with_items:
        - { from: "zsh/sources", to: ".zsh" }
        - { from: "zsh/zshrc", to: ".zshrc" }
        - { from: "zsh/zprofile", to: ".zprofile" }
        - { from: "git/gitconfig", to: ".gitconfig" }
        - { from: "nvim/init.vim", to: ".config/nvim/init.vim" }
        - { from: "nvim/vim-plug/plug.vim", to: ".config/nvim/autoload/plug.vim" }
        - { from: "nvim/vim-plug/plug.vim", to: ".config/nvim/autoload/plug.vim" }
        - { from: "i3/config", to: ".i3/config" }
        - { from: "x11/Xresources", to: ".Xresources" }
        - { from: "tmux/tmux.conf", to: ".tmux.conf" }
